name             'chef-wordpresswrapper'
maintainer       'Michael Ruxsaksriskul'
maintainer_email 'mruxsaksri@gannett.com'
license          'All rights reserved'
description      'Installs/Configures chef-wordpresswrapper'
long_description 'Installs/Configures chef-wordpresswrapper'
version          '0.1.0'

depends 'gdp-base-linux'
depends 'php'
depends 'php-fpm'
depends 'nginx', '>=2.7.4'
depends 'ark'
